// named imports
import { AppBar, SideBar } from '@/components/globals'

// default imports
import './globals.css'

export const metadata = {
  title: 'Finvisor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='text-white'>
        <div className='grid grid-cols-10 '>
          <div className='col-span-2 bg-[#000000]'>
            <SideBar />
          </div>

          <div className='col-span-8 bg-[#191825]'>
            <AppBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
